name: Update readme ⭐️ progress

on:
    schedule:
        - cron: "0 6 1-20 12 *" # 12:00 AM CST on Dec1-20
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        if: ${{ vars.AOC_ENABLED == 'true' }}
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: k2bd/advent-readme-stars@v1
              with:
                  userId: ${{ secrets.AOC_USER_ID }}
                  sessionCookie: ${{ secrets.AOC_SESSION }}
                  year: ${{ secrets.AOC_YEAR }}
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "update readme progress"
